nf_core_version: 4.0.3
repository_type: pipeline
template:
  author: "Sébastien Guizard (@sguizard)"
  description: Genes and transcripts annotation with Isoseq using uLTRA and TAMA
  force: false
  is_nfcore: true
  name: isoseq
  org: nf-core
  outdir: .
  version: 2.1.0dev
lint:
  files_unchanged:
    - assets/nf-core-isoseq_logo_light.png
    - docs/images/nf-core-isoseq_logo_light.png
    - docs/images/nf-core-isoseq_logo_dark.png
