lint:
  files_unchanged:
    - assets/nf-core-isoseq_logo_light.png
    - docs/images/nf-core-isoseq_logo_light.png
    - docs/images/nf-core-isoseq_logo_dark.png
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: "S\xE9bastien Guizard (@sguizard)"
  description: Genes and transcripts annotation with Isoseq using uLTRA and TAMA
  force: false
  is_nfcore: true
  name: isoseq
  org: nf-core
  outdir: .
  version: 3.0.0
